# Generated by Django 6.0.1 on 2026-01-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(verbose_name=50)),
                ('familiya', models.CharField(verbose_name=50)),
                ('raqam', models.CharField(verbose_name=20)),
                ('email', models.EmailField(max_length=254)),
                ('xabar', models.TextField()),
            ],
        ),
    ]
