# Generated by Django 6.0.1 on 2026-01-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='xabar',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='familiya',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ism',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='raqam',
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
